### ISSUE TITLE
关于设置问题

### ISSUE THREAD

**Issue by JoseyDon** [yumemor/hexo-theme-varaint#1]
请问那个微笑着的狗脸在哪里更换？谢谢。

**Comment by akarineren** [comment]
在主题的 _config.yml 配置文件中，

``` yaml
headimg: http://oct8d1mqf.bkt.clouddn.com/2016-10-17-15%3A42%3A28.jpg
```

**Comment by JoseyDon** [comment]
请问您的多说通用代码在哪个文件里面？找了半天没找到，我复制到layout里面的ejs文件之里，页面会跳出弹窗，并且多说的样式也没有了。谢谢。

**Comment by akarineren** [comment]
默认情况下，你如果想启用评论 可以直接在

``` yaml
comments:
  duoshuo_username:  多说用户名
```

如果你想个性化，多说评论文件在：`hexo-theme-varaint/layout/_partial/post/duoshuo-comment.ejs`

**Comment by jasoncheng911** [comment]
@JoseyDon hey，这个主题没有archive和tag  你有自己写这个页面吗？

**Comment by akarineren** [comment]
目前还没有
