### ISSUE TITLE
兄弟，可不可以实现文章置顶的功能？

### ISSUE THREAD

**Issue by zhongzilu** [yumemor/hexo-theme-varaint#10]
另外有件事，我fork了一个版本，并新增了一个网站统计功能，你看我的提交记录就知道修改了哪些文件

**Comment by akarineren** [comment]
你可以提交到我这里的 master 分支 如果没有什么问题 我会即时 merge，增加的功能还是麻烦写一下描述哈

**Comment by zhongzilu** [comment]
OK
