### ISSUE TITLE
您好 我想问一下这个主题支持分页展示文章吗？

### ISSUE THREAD

**Issue by u3u** [yumemor/hexo-theme-varaint#13]
很喜欢这款主题 设计的很棒！
就是目前还不太清楚是否支持分页显示文章 我目前文章也不多 所以看不出来

**Comment by u3u** [comment]
如果不支持的话我就自己写一个吧qwq

**Comment by akarineren** [comment]
可以的哦，目前暂时没有 category 和 tag 页面。

**Comment by u3u** [comment]
@yumemor 
好哒 那就好！
