### ISSUE TITLE
关于lib.js

### ISSUE THREAD

**Issue by lou-lan** [yumemor/hexo-theme-varaint#14]
请问lib.js里是什么代码？如果只使用banner特效，应该提取那一部分？

**Comment by akarineren** [comment]
lib.js 是项目用到的第三方依赖的压缩版本。

如果想看 banner 下的波浪特效实现 在 module.js 里面 。

**Comment by lou-lan** [comment]
非常感谢，不过依赖太多，我想提取出来。
