### ISSUE TITLE
关于表格

### ISSUE THREAD

**Issue by sepwolves** [yumemor/hexo-theme-varaint#2]
表格变得非常难看，是bug吗？

![ddd](https://cloud.githubusercontent.com/assets/4755874/20553161/016316ae-b18d-11e6-95f7-7ab4eda9276b.png)
）

**Comment by akarineren** [comment]
应该是没有对应的 css 实现，你是怎么添加表格的？ 贴出来吧

**Comment by sepwolves** [comment]
markdown里不是有表格吗？我用其他主题的时候是可以显示表格的呀。。比如next主题。。

**Comment by akarineren** [comment]
markdown 的确有表格，但是显示样式是需要 css 来操作的，当前这个主题显然是没有实现的 所以我建议你把表格的写法贴出来，我在后面的版本升级中 会添加表格的支持

**Comment by sepwolves** [comment]
|1701   |	1705         |	价差1705-1701|	备注       |
|-------------|:-------------:|:-------------:|------------|
|2016/11/21  	|17200（买入）	 |17700（卖出)    |	500       |
|2016/12/30  	|18500           |18800       |300          |

语法其实好简单的啊。

**Comment by sepwolves** [comment]
'''markdown
|1701   |	1705         |	价差1705-1701|	备注       |
|-------------|:-------------:|:-------------:|------------|
|2016/11/21  	|17200（买入）	 |17700（卖出)    |	500       |
|2016/12/30  	|18500           |18800       |300          |
'''

**Comment by akarineren** [comment]
现在已添加对于表格的支持， 请重新 clone 下主题就好了

**Comment by sepwolves** [comment]
你效率真高啊!

**Comment by sepwolves** [comment]
重新下载了你的主题，表格问题解决了。但是banner问题还是依旧。看来会不会是我的配置文件的问题？
