### ISSUE TITLE
关于搜索的问题

### ISSUE THREAD

**Issue by Moreki** [yumemor/hexo-theme-varaint#20]
请问一下，在http://gushi.li 进行搜索是正常的，您提供的预览地址和我安装的主题都不能完成搜索，和故事里不一样，这边全部用了谷歌搜索，如何可以做到故事里那样的搜索结果？谢谢。

**Comment by akarineren** [comment]
这个主题搜索是使用 google site: 的方式搜索的 目前没有站内搜索的功能。

**Comment by Moreki** [comment]
gushi.li是站内搜索，好吧，目前可以先关闭搜索功能了。谢谢

**Comment by akarineren** [comment]
不客气
