### ISSUE TITLE
banner为什么会消失呢？

### ISSUE THREAD

**Issue by sepwolves** [yumemor/hexo-theme-varaint#3]
我一开始使用你的varaint主题的时候，我的网站上还能显示banner。但是后来不知道为什么就不能看了。然后页面上面留了一大片空白，很难看。这个是为什么呢？

**Comment by akarineren** [comment]
由于所有的 banner 文件并没有放在 cdn 上，是默认交给 github 托管，本身国内访问 github 就比较慢 图片加载可能会失败，不过你可以放在 cdn 上面

**Comment by yumemor** [comment]
由于所有的 banner 文件并没有放在 cdn 上，是默认交给 github 托管，本身国内访问 github 就比较慢 图片加载可能会失败，不过你可以放在 cdn 上面

**Comment by sepwolves** [comment]
问题是我在本地上也失败了。我不知道是什么缘故。因为你的banner是放在本地电脑上的呀，不应该看不见的呀。。
我很喜欢你的banner。。

**Comment by akarineren** [comment]
这个问题一般都是图片路径没有找到，你要检查banner加载的图片地址是否可以访问 主题本身是没有这个问题的

**Comment by sepwolves** [comment]
为什么要close掉啊。这样的话类似的问题如果前面有人提过不就看不到了吗？

**Comment by akarineren** [comment]
你的图片不显示 一定是路径的问题 稍微有点基础的都会抓个包看看怎么回事，如果你觉得麻烦 把整个博客目录先 clean，重新  clone 这个主题 。

close 掉问题是因为这个不是主题本身的问题，只是人为的误操作 ，lssues 是支持搜索的  即使是关闭别人也能看得到 。

**Comment by sepwolves** [comment]
我可以加你即时通讯工具来咨询吗？比如qq或者微信啥的？
好奇怪，可是我并没有修改过路径啊。
至于抓包，对我来说根本就是抓瞎了。我基本上没有什么前端基础。。

**Comment by akarineren** [comment]
加我微信吧  yumemor
